# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\CLion\CLion 2018.1.2\bin\cmake\bin\cmake.exe"

# The command to remove a file.
RM = "D:\CLion\CLion 2018.1.2\bin\cmake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Dev\RogueGame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Dev\RogueGame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install\local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	echo >nul && "D:\CLion\CLion 2018.1.2\bin\cmake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install\local

# Special rule for the target install/local
install\local\fast: preinstall\fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	echo >nul && "D:\CLion\CLion 2018.1.2\bin\cmake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install\local\fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	echo >nul && "D:\CLion\CLion 2018.1.2\bin\cmake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install\fast: preinstall\fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	echo >nul && "D:\CLion\CLion 2018.1.2\bin\cmake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install\fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	echo >nul && "D:\CLion\CLion 2018.1.2\bin\cmake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "D:\CLion\CLion 2018.1.2\bin\cmake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"assimp-bin\" \"assimp-dev\" \"libassimp4.1.0\" \"libassimp4.1.0-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components\fast: list_install_components

.PHONY : list_install_components\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Dev\RogueGame\CMakeFiles D:\Dev\RogueGame\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Dev\RogueGame\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RogueGame

# Build rule for target.
RogueGame: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) RogueGame
.PHONY : RogueGame

# fast build rule for target.
RogueGame\fast:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\build
.PHONY : RogueGame\fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) imgui
.PHONY : imgui

# fast build rule for target.
imgui\fast:
	$(MAKE) -f deps\CMakeFiles\imgui.dir\build.make /nologo -$(MAKEFLAGS) deps\CMakeFiles\imgui.dir\build
.PHONY : imgui\fast

#=============================================================================
# Target rules for targets named shaderc

# Build rule for target.
shaderc: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) shaderc
.PHONY : shaderc

# fast build rule for target.
shaderc\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\shaderc.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\shaderc.dir\build
.PHONY : shaderc\fast

#=============================================================================
# Target rules for targets named pvrtc

# Build rule for target.
pvrtc: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) pvrtc
.PHONY : pvrtc

# fast build rule for target.
pvrtc\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\pvrtc.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\pvrtc.dir\build
.PHONY : pvrtc\fast

#=============================================================================
# Target rules for targets named iqa

# Build rule for target.
iqa: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) iqa
.PHONY : iqa

# fast build rule for target.
iqa\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\iqa.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\iqa.dir\build
.PHONY : iqa\fast

#=============================================================================
# Target rules for targets named glslang

# Build rule for target.
glslang: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) glslang
.PHONY : glslang

# fast build rule for target.
glslang\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\glslang.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\glslang.dir\build
.PHONY : glslang\fast

#=============================================================================
# Target rules for targets named edtaa3

# Build rule for target.
edtaa3: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) edtaa3
.PHONY : edtaa3

# fast build rule for target.
edtaa3\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\edtaa3.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\edtaa3.dir\build
.PHONY : edtaa3\fast

#=============================================================================
# Target rules for targets named mesa

# Build rule for target.
mesa: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) mesa
.PHONY : mesa

# fast build rule for target.
mesa\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\mesa.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\mesa.dir\build
.PHONY : mesa\fast

#=============================================================================
# Target rules for targets named bx

# Build rule for target.
bx: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) bx
.PHONY : bx

# fast build rule for target.
bx\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\bx.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\bx.dir\build
.PHONY : bx\fast

#=============================================================================
# Target rules for targets named astc

# Build rule for target.
astc: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) astc
.PHONY : astc

# fast build rule for target.
astc\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\astc.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\astc.dir\build
.PHONY : astc\fast

#=============================================================================
# Target rules for targets named etc1

# Build rule for target.
etc1: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) etc1
.PHONY : etc1

# fast build rule for target.
etc1\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\etc1.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\etc1.dir\build
.PHONY : etc1\fast

#=============================================================================
# Target rules for targets named etc2

# Build rule for target.
etc2: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) etc2
.PHONY : etc2

# fast build rule for target.
etc2\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\etc2.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\etc2.dir\build
.PHONY : etc2\fast

#=============================================================================
# Target rules for targets named squish

# Build rule for target.
squish: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) squish
.PHONY : squish

# fast build rule for target.
squish\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\squish.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\squish.dir\build
.PHONY : squish\fast

#=============================================================================
# Target rules for targets named example-common

# Build rule for target.
example-common: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) example-common
.PHONY : example-common

# fast build rule for target.
example-common\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\example-common.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\example-common.dir\build
.PHONY : example-common\fast

#=============================================================================
# Target rules for targets named texturec

# Build rule for target.
texturec: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) texturec
.PHONY : texturec

# fast build rule for target.
texturec\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\texturec.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\texturec.dir\build
.PHONY : texturec\fast

#=============================================================================
# Target rules for targets named nvtt

# Build rule for target.
nvtt: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) nvtt
.PHONY : nvtt

# fast build rule for target.
nvtt\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\nvtt.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\nvtt.dir\build
.PHONY : nvtt\fast

#=============================================================================
# Target rules for targets named bimg

# Build rule for target.
bimg: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) bimg
.PHONY : bimg

# fast build rule for target.
bimg\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\bimg.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\bimg.dir\build
.PHONY : bimg\fast

#=============================================================================
# Target rules for targets named bgfx

# Build rule for target.
bgfx: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) bgfx
.PHONY : bgfx

# fast build rule for target.
bgfx\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\bgfx.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\bgfx.dir\build
.PHONY : bgfx\fast

#=============================================================================
# Target rules for targets named forsyth-too

# Build rule for target.
forsyth-too: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) forsyth-too
.PHONY : forsyth-too

# fast build rule for target.
forsyth-too\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\forsyth-too.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\forsyth-too.dir\build
.PHONY : forsyth-too\fast

#=============================================================================
# Target rules for targets named ib-compress

# Build rule for target.
ib-compress: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ib-compress
.PHONY : ib-compress

# fast build rule for target.
ib-compress\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\ib-compress.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\ib-compress.dir\build
.PHONY : ib-compress\fast

#=============================================================================
# Target rules for targets named geometryc

# Build rule for target.
geometryc: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) geometryc
.PHONY : geometryc

# fast build rule for target.
geometryc\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\geometryc.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\geometryc.dir\build
.PHONY : geometryc\fast

#=============================================================================
# Target rules for targets named fcpp

# Build rule for target.
fcpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) fcpp
.PHONY : fcpp

# fast build rule for target.
fcpp\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\fcpp.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\fcpp.dir\build
.PHONY : fcpp\fast

#=============================================================================
# Target rules for targets named glcpp

# Build rule for target.
glcpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) glcpp
.PHONY : glcpp

# fast build rule for target.
glcpp\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\glcpp.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\glcpp.dir\build
.PHONY : glcpp\fast

#=============================================================================
# Target rules for targets named glsl-optimizer

# Build rule for target.
glsl-optimizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) glsl-optimizer
.PHONY : glsl-optimizer

# fast build rule for target.
glsl-optimizer\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\glsl-optimizer.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\glsl-optimizer.dir\build
.PHONY : glsl-optimizer\fast

#=============================================================================
# Target rules for targets named texturev

# Build rule for target.
texturev: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) texturev
.PHONY : texturev

# fast build rule for target.
texturev\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\texturev.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\texturev.dir\build
.PHONY : texturev\fast

#=============================================================================
# Target rules for targets named dear-imgui

# Build rule for target.
dear-imgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) dear-imgui
.PHONY : dear-imgui

# fast build rule for target.
dear-imgui\fast:
	$(MAKE) -f deps\bgfx.cmake\CMakeFiles\dear-imgui.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\CMakeFiles\dear-imgui.dir\build
.PHONY : dear-imgui\fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) glfw
.PHONY : glfw

# fast build rule for target.
glfw\fast:
	$(MAKE) -f deps\glfw\src\CMakeFiles\glfw.dir\build.make /nologo -$(MAKEFLAGS) deps\glfw\src\CMakeFiles\glfw.dir\build
.PHONY : glfw\fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall\fast:
	$(MAKE) -f deps\assimp\CMakeFiles\uninstall.dir\build.make /nologo -$(MAKEFLAGS) deps\assimp\CMakeFiles\uninstall.dir\build
.PHONY : uninstall\fast

#=============================================================================
# Target rules for targets named UpdateAssimpLibsDebugSymbolsAndDLLs

# Build rule for target.
UpdateAssimpLibsDebugSymbolsAndDLLs: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) UpdateAssimpLibsDebugSymbolsAndDLLs
.PHONY : UpdateAssimpLibsDebugSymbolsAndDLLs

# fast build rule for target.
UpdateAssimpLibsDebugSymbolsAndDLLs\fast:
	$(MAKE) -f deps\assimp\CMakeFiles\UpdateAssimpLibsDebugSymbolsAndDLLs.dir\build.make /nologo -$(MAKEFLAGS) deps\assimp\CMakeFiles\UpdateAssimpLibsDebugSymbolsAndDLLs.dir\build
.PHONY : UpdateAssimpLibsDebugSymbolsAndDLLs\fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) zlib
.PHONY : zlib

# fast build rule for target.
zlib\fast:
	$(MAKE) -f deps\assimp\contrib\zlib\CMakeFiles\zlib.dir\build.make /nologo -$(MAKEFLAGS) deps\assimp\contrib\zlib\CMakeFiles\zlib.dir\build
.PHONY : zlib\fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic\fast:
	$(MAKE) -f deps\assimp\contrib\zlib\CMakeFiles\zlibstatic.dir\build.make /nologo -$(MAKEFLAGS) deps\assimp\contrib\zlib\CMakeFiles\zlibstatic.dir\build
.PHONY : zlibstatic\fast

#=============================================================================
# Target rules for targets named IrrXML

# Build rule for target.
IrrXML: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) IrrXML
.PHONY : IrrXML

# fast build rule for target.
IrrXML\fast:
	$(MAKE) -f deps\assimp\contrib\irrXML\CMakeFiles\IrrXML.dir\build.make /nologo -$(MAKEFLAGS) deps\assimp\contrib\irrXML\CMakeFiles\IrrXML.dir\build
.PHONY : IrrXML\fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) assimp
.PHONY : assimp

# fast build rule for target.
assimp\fast:
	$(MAKE) -f deps\assimp\code\CMakeFiles\assimp.dir\build.make /nologo -$(MAKEFLAGS) deps\assimp\code\CMakeFiles\assimp.dir\build
.PHONY : assimp\fast

#=============================================================================
# Target rules for targets named assimp_cmd

# Build rule for target.
assimp_cmd: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) assimp_cmd
.PHONY : assimp_cmd

# fast build rule for target.
assimp_cmd\fast:
	$(MAKE) -f deps\assimp\tools\assimp_cmd\CMakeFiles\assimp_cmd.dir\build.make /nologo -$(MAKEFLAGS) deps\assimp\tools\assimp_cmd\CMakeFiles\assimp_cmd.dir\build
.PHONY : assimp_cmd\fast

#=============================================================================
# Target rules for targets named unit

# Build rule for target.
unit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) unit
.PHONY : unit

# fast build rule for target.
unit\fast:
	$(MAKE) -f deps\assimp\test\CMakeFiles\unit.dir\build.make /nologo -$(MAKEFLAGS) deps\assimp\test\CMakeFiles\unit.dir\build
.PHONY : unit\fast

#=============================================================================
# Target rules for targets named brtshaderc

# Build rule for target.
brtshaderc: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) brtshaderc
.PHONY : brtshaderc

# fast build rule for target.
brtshaderc\fast:
	$(MAKE) -f deps\bgfx.cmake\bgfx\.build\projects\cmake\brtshaderc\CMakeFiles\brtshaderc.dir\build.make /nologo -$(MAKEFLAGS) deps\bgfx.cmake\bgfx\.build\projects\cmake\brtshaderc\CMakeFiles\brtshaderc.dir\build
.PHONY : brtshaderc\fast

src\app\Application.obj: src\app\Application.cpp.obj

.PHONY : src\app\Application.obj

# target to build an object file
src\app\Application.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\app\Application.cpp.obj
.PHONY : src\app\Application.cpp.obj

src\app\Application.i: src\app\Application.cpp.i

.PHONY : src\app\Application.i

# target to preprocess a source file
src\app\Application.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\app\Application.cpp.i
.PHONY : src\app\Application.cpp.i

src\app\Application.s: src\app\Application.cpp.s

.PHONY : src\app\Application.s

# target to generate assembly for a file
src\app\Application.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\app\Application.cpp.s
.PHONY : src\app\Application.cpp.s

src\assets\AssetUtils.obj: src\assets\AssetUtils.cpp.obj

.PHONY : src\assets\AssetUtils.obj

# target to build an object file
src\assets\AssetUtils.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\assets\AssetUtils.cpp.obj
.PHONY : src\assets\AssetUtils.cpp.obj

src\assets\AssetUtils.i: src\assets\AssetUtils.cpp.i

.PHONY : src\assets\AssetUtils.i

# target to preprocess a source file
src\assets\AssetUtils.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\assets\AssetUtils.cpp.i
.PHONY : src\assets\AssetUtils.cpp.i

src\assets\AssetUtils.s: src\assets\AssetUtils.cpp.s

.PHONY : src\assets\AssetUtils.s

# target to generate assembly for a file
src\assets\AssetUtils.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\assets\AssetUtils.cpp.s
.PHONY : src\assets\AssetUtils.cpp.s

src\assets\Assets.obj: src\assets\Assets.cpp.obj

.PHONY : src\assets\Assets.obj

# target to build an object file
src\assets\Assets.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\assets\Assets.cpp.obj
.PHONY : src\assets\Assets.cpp.obj

src\assets\Assets.i: src\assets\Assets.cpp.i

.PHONY : src\assets\Assets.i

# target to preprocess a source file
src\assets\Assets.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\assets\Assets.cpp.i
.PHONY : src\assets\Assets.cpp.i

src\assets\Assets.s: src\assets\Assets.cpp.s

.PHONY : src\assets\Assets.s

# target to generate assembly for a file
src\assets\Assets.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\assets\Assets.cpp.s
.PHONY : src\assets\Assets.cpp.s

src\assets\tinyfiledialogs.obj: src\assets\tinyfiledialogs.cpp.obj

.PHONY : src\assets\tinyfiledialogs.obj

# target to build an object file
src\assets\tinyfiledialogs.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\assets\tinyfiledialogs.cpp.obj
.PHONY : src\assets\tinyfiledialogs.cpp.obj

src\assets\tinyfiledialogs.i: src\assets\tinyfiledialogs.cpp.i

.PHONY : src\assets\tinyfiledialogs.i

# target to preprocess a source file
src\assets\tinyfiledialogs.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\assets\tinyfiledialogs.cpp.i
.PHONY : src\assets\tinyfiledialogs.cpp.i

src\assets\tinyfiledialogs.s: src\assets\tinyfiledialogs.cpp.s

.PHONY : src\assets\tinyfiledialogs.s

# target to generate assembly for a file
src\assets\tinyfiledialogs.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\assets\tinyfiledialogs.cpp.s
.PHONY : src\assets\tinyfiledialogs.cpp.s

src\editor\Editor.obj: src\editor\Editor.cpp.obj

.PHONY : src\editor\Editor.obj

# target to build an object file
src\editor\Editor.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\Editor.cpp.obj
.PHONY : src\editor\Editor.cpp.obj

src\editor\Editor.i: src\editor\Editor.cpp.i

.PHONY : src\editor\Editor.i

# target to preprocess a source file
src\editor\Editor.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\Editor.cpp.i
.PHONY : src\editor\Editor.cpp.i

src\editor\Editor.s: src\editor\Editor.cpp.s

.PHONY : src\editor\Editor.s

# target to generate assembly for a file
src\editor\Editor.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\Editor.cpp.s
.PHONY : src\editor\Editor.cpp.s

src\editor\FileViewer.obj: src\editor\FileViewer.cpp.obj

.PHONY : src\editor\FileViewer.obj

# target to build an object file
src\editor\FileViewer.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\FileViewer.cpp.obj
.PHONY : src\editor\FileViewer.cpp.obj

src\editor\FileViewer.i: src\editor\FileViewer.cpp.i

.PHONY : src\editor\FileViewer.i

# target to preprocess a source file
src\editor\FileViewer.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\FileViewer.cpp.i
.PHONY : src\editor\FileViewer.cpp.i

src\editor\FileViewer.s: src\editor\FileViewer.cpp.s

.PHONY : src\editor\FileViewer.s

# target to generate assembly for a file
src\editor\FileViewer.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\FileViewer.cpp.s
.PHONY : src\editor\FileViewer.cpp.s

src\editor\ImGuizmo.obj: src\editor\ImGuizmo.cpp.obj

.PHONY : src\editor\ImGuizmo.obj

# target to build an object file
src\editor\ImGuizmo.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\ImGuizmo.cpp.obj
.PHONY : src\editor\ImGuizmo.cpp.obj

src\editor\ImGuizmo.i: src\editor\ImGuizmo.cpp.i

.PHONY : src\editor\ImGuizmo.i

# target to preprocess a source file
src\editor\ImGuizmo.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\ImGuizmo.cpp.i
.PHONY : src\editor\ImGuizmo.cpp.i

src\editor\ImGuizmo.s: src\editor\ImGuizmo.cpp.s

.PHONY : src\editor\ImGuizmo.s

# target to generate assembly for a file
src\editor\ImGuizmo.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\ImGuizmo.cpp.s
.PHONY : src\editor\ImGuizmo.cpp.s

src\editor\Logger.obj: src\editor\Logger.cpp.obj

.PHONY : src\editor\Logger.obj

# target to build an object file
src\editor\Logger.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\Logger.cpp.obj
.PHONY : src\editor\Logger.cpp.obj

src\editor\Logger.i: src\editor\Logger.cpp.i

.PHONY : src\editor\Logger.i

# target to preprocess a source file
src\editor\Logger.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\Logger.cpp.i
.PHONY : src\editor\Logger.cpp.i

src\editor\Logger.s: src\editor\Logger.cpp.s

.PHONY : src\editor\Logger.s

# target to generate assembly for a file
src\editor\Logger.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\Logger.cpp.s
.PHONY : src\editor\Logger.cpp.s

src\editor\SceneWindow.obj: src\editor\SceneWindow.cpp.obj

.PHONY : src\editor\SceneWindow.obj

# target to build an object file
src\editor\SceneWindow.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\SceneWindow.cpp.obj
.PHONY : src\editor\SceneWindow.cpp.obj

src\editor\SceneWindow.i: src\editor\SceneWindow.cpp.i

.PHONY : src\editor\SceneWindow.i

# target to preprocess a source file
src\editor\SceneWindow.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\SceneWindow.cpp.i
.PHONY : src\editor\SceneWindow.cpp.i

src\editor\SceneWindow.s: src\editor\SceneWindow.cpp.s

.PHONY : src\editor\SceneWindow.s

# target to generate assembly for a file
src\editor\SceneWindow.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\editor\SceneWindow.cpp.s
.PHONY : src\editor\SceneWindow.cpp.s

src\entity\Entities.obj: src\entity\Entities.cpp.obj

.PHONY : src\entity\Entities.obj

# target to build an object file
src\entity\Entities.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\entity\Entities.cpp.obj
.PHONY : src\entity\Entities.cpp.obj

src\entity\Entities.i: src\entity\Entities.cpp.i

.PHONY : src\entity\Entities.i

# target to preprocess a source file
src\entity\Entities.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\entity\Entities.cpp.i
.PHONY : src\entity\Entities.cpp.i

src\entity\Entities.s: src\entity\Entities.cpp.s

.PHONY : src\entity\Entities.s

# target to generate assembly for a file
src\entity\Entities.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\entity\Entities.cpp.s
.PHONY : src\entity\Entities.cpp.s

src\entity\Generated.obj: src\entity\Generated.cpp.obj

.PHONY : src\entity\Generated.obj

# target to build an object file
src\entity\Generated.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\entity\Generated.cpp.obj
.PHONY : src\entity\Generated.cpp.obj

src\entity\Generated.i: src\entity\Generated.cpp.i

.PHONY : src\entity\Generated.i

# target to preprocess a source file
src\entity\Generated.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\entity\Generated.cpp.i
.PHONY : src\entity\Generated.cpp.i

src\entity\Generated.s: src\entity\Generated.cpp.s

.PHONY : src\entity\Generated.s

# target to generate assembly for a file
src\entity\Generated.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\entity\Generated.cpp.s
.PHONY : src\entity\Generated.cpp.s

src\entity\Scene.obj: src\entity\Scene.cpp.obj

.PHONY : src\entity\Scene.obj

# target to build an object file
src\entity\Scene.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\entity\Scene.cpp.obj
.PHONY : src\entity\Scene.cpp.obj

src\entity\Scene.i: src\entity\Scene.cpp.i

.PHONY : src\entity\Scene.i

# target to preprocess a source file
src\entity\Scene.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\entity\Scene.cpp.i
.PHONY : src\entity\Scene.cpp.i

src\entity\Scene.s: src\entity\Scene.cpp.s

.PHONY : src\entity\Scene.s

# target to generate assembly for a file
src\entity\Scene.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\entity\Scene.cpp.s
.PHONY : src\entity\Scene.cpp.s

src\input\Input.obj: src\input\Input.cpp.obj

.PHONY : src\input\Input.obj

# target to build an object file
src\input\Input.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\input\Input.cpp.obj
.PHONY : src\input\Input.cpp.obj

src\input\Input.i: src\input\Input.cpp.i

.PHONY : src\input\Input.i

# target to preprocess a source file
src\input\Input.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\input\Input.cpp.i
.PHONY : src\input\Input.cpp.i

src\input\Input.s: src\input\Input.cpp.s

.PHONY : src\input\Input.s

# target to generate assembly for a file
src\input\Input.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\input\Input.cpp.s
.PHONY : src\input\Input.cpp.s

src\main.obj: src\main.cpp.obj

.PHONY : src\main.obj

# target to build an object file
src\main.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\main.cpp.obj
.PHONY : src\main.cpp.obj

src\main.i: src\main.cpp.i

.PHONY : src\main.i

# target to preprocess a source file
src\main.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\main.cpp.i
.PHONY : src\main.cpp.i

src\main.s: src\main.cpp.s

.PHONY : src\main.s

# target to generate assembly for a file
src\main.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\main.cpp.s
.PHONY : src\main.cpp.s

src\physics\Collision.obj: src\physics\Collision.cpp.obj

.PHONY : src\physics\Collision.obj

# target to build an object file
src\physics\Collision.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\physics\Collision.cpp.obj
.PHONY : src\physics\Collision.cpp.obj

src\physics\Collision.i: src\physics\Collision.cpp.i

.PHONY : src\physics\Collision.i

# target to preprocess a source file
src\physics\Collision.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\physics\Collision.cpp.i
.PHONY : src\physics\Collision.cpp.i

src\physics\Collision.s: src\physics\Collision.cpp.s

.PHONY : src\physics\Collision.s

# target to generate assembly for a file
src\physics\Collision.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\physics\Collision.cpp.s
.PHONY : src\physics\Collision.cpp.s

src\physics\Physics.obj: src\physics\Physics.cpp.obj

.PHONY : src\physics\Physics.obj

# target to build an object file
src\physics\Physics.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\physics\Physics.cpp.obj
.PHONY : src\physics\Physics.cpp.obj

src\physics\Physics.i: src\physics\Physics.cpp.i

.PHONY : src\physics\Physics.i

# target to preprocess a source file
src\physics\Physics.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\physics\Physics.cpp.i
.PHONY : src\physics\Physics.cpp.i

src\physics\Physics.s: src\physics\Physics.cpp.s

.PHONY : src\physics\Physics.s

# target to generate assembly for a file
src\physics\Physics.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\physics\Physics.cpp.s
.PHONY : src\physics\Physics.cpp.s

src\physics\Time.obj: src\physics\Time.cpp.obj

.PHONY : src\physics\Time.obj

# target to build an object file
src\physics\Time.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\physics\Time.cpp.obj
.PHONY : src\physics\Time.cpp.obj

src\physics\Time.i: src\physics\Time.cpp.i

.PHONY : src\physics\Time.i

# target to preprocess a source file
src\physics\Time.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\physics\Time.cpp.i
.PHONY : src\physics\Time.cpp.i

src\physics\Time.s: src\physics\Time.cpp.s

.PHONY : src\physics\Time.s

# target to generate assembly for a file
src\physics\Time.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\physics\Time.cpp.s
.PHONY : src\physics\Time.cpp.s

src\rendering\Renderer.obj: src\rendering\Renderer.cpp.obj

.PHONY : src\rendering\Renderer.obj

# target to build an object file
src\rendering\Renderer.cpp.obj:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\rendering\Renderer.cpp.obj
.PHONY : src\rendering\Renderer.cpp.obj

src\rendering\Renderer.i: src\rendering\Renderer.cpp.i

.PHONY : src\rendering\Renderer.i

# target to preprocess a source file
src\rendering\Renderer.cpp.i:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\rendering\Renderer.cpp.i
.PHONY : src\rendering\Renderer.cpp.i

src\rendering\Renderer.s: src\rendering\Renderer.cpp.s

.PHONY : src\rendering\Renderer.s

# target to generate assembly for a file
src\rendering\Renderer.cpp.s:
	$(MAKE) -f CMakeFiles\RogueGame.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\RogueGame.dir\src\rendering\Renderer.cpp.s
.PHONY : src\rendering\Renderer.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... RogueGame
	@echo ... install/local
	@echo ... install
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... list_install_components
	@echo ... imgui
	@echo ... shaderc
	@echo ... pvrtc
	@echo ... iqa
	@echo ... glslang
	@echo ... edtaa3
	@echo ... mesa
	@echo ... bx
	@echo ... astc
	@echo ... etc1
	@echo ... etc2
	@echo ... squish
	@echo ... example-common
	@echo ... texturec
	@echo ... nvtt
	@echo ... bimg
	@echo ... bgfx
	@echo ... forsyth-too
	@echo ... ib-compress
	@echo ... geometryc
	@echo ... fcpp
	@echo ... glcpp
	@echo ... glsl-optimizer
	@echo ... texturev
	@echo ... dear-imgui
	@echo ... glfw
	@echo ... uninstall
	@echo ... UpdateAssimpLibsDebugSymbolsAndDLLs
	@echo ... zlib
	@echo ... zlibstatic
	@echo ... IrrXML
	@echo ... assimp
	@echo ... assimp_cmd
	@echo ... unit
	@echo ... brtshaderc
	@echo ... src/app/Application.obj
	@echo ... src/app/Application.i
	@echo ... src/app/Application.s
	@echo ... src/assets/AssetUtils.obj
	@echo ... src/assets/AssetUtils.i
	@echo ... src/assets/AssetUtils.s
	@echo ... src/assets/Assets.obj
	@echo ... src/assets/Assets.i
	@echo ... src/assets/Assets.s
	@echo ... src/assets/tinyfiledialogs.obj
	@echo ... src/assets/tinyfiledialogs.i
	@echo ... src/assets/tinyfiledialogs.s
	@echo ... src/editor/Editor.obj
	@echo ... src/editor/Editor.i
	@echo ... src/editor/Editor.s
	@echo ... src/editor/FileViewer.obj
	@echo ... src/editor/FileViewer.i
	@echo ... src/editor/FileViewer.s
	@echo ... src/editor/ImGuizmo.obj
	@echo ... src/editor/ImGuizmo.i
	@echo ... src/editor/ImGuizmo.s
	@echo ... src/editor/Logger.obj
	@echo ... src/editor/Logger.i
	@echo ... src/editor/Logger.s
	@echo ... src/editor/SceneWindow.obj
	@echo ... src/editor/SceneWindow.i
	@echo ... src/editor/SceneWindow.s
	@echo ... src/entity/Entities.obj
	@echo ... src/entity/Entities.i
	@echo ... src/entity/Entities.s
	@echo ... src/entity/Generated.obj
	@echo ... src/entity/Generated.i
	@echo ... src/entity/Generated.s
	@echo ... src/entity/Scene.obj
	@echo ... src/entity/Scene.i
	@echo ... src/entity/Scene.s
	@echo ... src/input/Input.obj
	@echo ... src/input/Input.i
	@echo ... src/input/Input.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/physics/Collision.obj
	@echo ... src/physics/Collision.i
	@echo ... src/physics/Collision.s
	@echo ... src/physics/Physics.obj
	@echo ... src/physics/Physics.i
	@echo ... src/physics/Physics.s
	@echo ... src/physics/Time.obj
	@echo ... src/physics/Time.i
	@echo ... src/physics/Time.s
	@echo ... src/rendering/Renderer.obj
	@echo ... src/rendering/Renderer.i
	@echo ... src/rendering/Renderer.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

